{% set version = "2.0.4" %}

package:
  name: pygrib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pygrib/pygrib-{{ version }}.tar.gz
  sha256: c3a828c1121c686814c2cfe281a7a3be196a22b9754306bf61c3fd65c31f1fcd
  patches:
    - fix-win-build.patch  # [win]
    - fix-openjpeg-lib.patch  # [win]
    - fix-png-windows.patch  # [win]

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - eccodes
    - jasper  # [not win]
    - openjpeg  # [win]
    - libpng
    - pyproj
    - zlib
    - numpy
  run:
    - python
    - setuptools
    - eccodes
    - jasper  # [not win]
    - openjpeg  # [win]
    - libpng
    - numpy
    - pyproj
    - zlib

test:
  imports:
    - pygrib
  commands:
    - grib_repack -h

about:
  home: https://github.com/jswhit/pygrib
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Python GRIB (editions 1 and 2) reader.'
  doc_url: https://jswhit.github.io/pygrib/
  dev_url: https://github.com/jswhit/pygrib

extra:
  recipe-maintainers:
    - dopplershift
    - jjhelmus
    - ocefpaf
